{{- if .Values.ingress.enabled }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: pdm-backend
  annotations:
    nginx.ingress.kubernetes.io/proxy-body-size: "50m"   # Allow large PDF uploads
spec:
  ingressClassName: nginx
  rules:
    - host: {{ .Values.ingress.host }}
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: pdm-backend
                port:
                  number: {{ .Values.service.port }}
{{- end }}