apiVersion: v1
kind: Secret
metadata:
  name: pdm-backend-secret
type: Opaque
stringData:
  database-url: "postgresql://{{ .Values.postgres.user }}:{{ .Values.postgres.password }}@pdm-postgres:5432/{{ .Values.postgres.database }}"
  postgres-password: {{ .Values.postgres.password | quote }}
