"""initial schema

Revision ID: b881186c7330
Revises: 
Create Date: 2026-06-04 16:53:29.378850

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision = 'b881186c7330'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('branches',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('repository_id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('base_commit_id', sa.Uuid(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('created_by', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['base_commit_id'], ['commits.id'], ),
    sa.ForeignKeyConstraint(['repository_id'], ['repositories.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('audit_events', sa.Column('timestamp', sa.DateTime(), nullable=False))
    op.add_column('audit_events', sa.Column('action', sa.String(length=50), nullable=False))
    op.add_column('audit_events', sa.Column('entity_type', sa.String(length=50), nullable=False))
    op.add_column('audit_events', sa.Column('entity_id', sa.String(length=100), nullable=True))
    op.add_column('audit_events', sa.Column('ip_address', sa.String(length=50), nullable=True))
    op.add_column('audit_events', sa.Column('is_breach', sa.Boolean(), nullable=False))
    op.drop_column('audit_events', 'created_at')
    op.drop_column('audit_events', 'event_type')
    op.add_column('bom_entries', sa.Column('assembly_id', sa.Uuid(), nullable=False))
    op.add_column('bom_entries', sa.Column('component_id', sa.Uuid(), nullable=False))
    op.add_column('bom_entries', sa.Column('find_number', sa.Integer(), nullable=True))
    op.drop_constraint('bom_entries_parent_document_id_fkey', 'bom_entries', type_='foreignkey')
    op.drop_constraint('bom_entries_child_document_id_fkey', 'bom_entries', type_='foreignkey')
    op.create_foreign_key(None, 'bom_entries', 'documents', ['component_id'], ['id'])
    op.create_foreign_key(None, 'bom_entries', 'documents', ['assembly_id'], ['id'])
    op.drop_column('bom_entries', 'parent_document_id')
    op.drop_column('bom_entries', 'child_document_id')
    op.add_column('commit_files', sa.Column('s3_key_svg', sa.String(length=500), nullable=True))
    op.add_column('commit_files', sa.Column('s3_key_pdf', sa.String(length=500), nullable=True))
    op.add_column('commit_files', sa.Column('content_hash', sa.String(length=64), nullable=True))
    op.add_column('commit_files', sa.Column('pdf_diff', sa.JSON(), nullable=True))
    op.drop_column('commit_files', 'svg_key')
    op.drop_column('commit_files', 'diff_key')
    op.add_column('commits', sa.Column('branch_id', sa.Uuid(), nullable=True))
    op.add_column('commits', sa.Column('parent_id', sa.Uuid(), nullable=True))
    op.add_column('commits', sa.Column('short_hash', sa.String(length=16), nullable=False))
    op.add_column('commits', sa.Column('is_local', sa.Boolean(), nullable=False))
    op.add_column('commits', sa.Column('diff_report', sa.JSON(), nullable=True))
    op.add_column('commits', sa.Column('protocol_violations', sa.JSON(), nullable=True))
    op.add_column('commits', sa.Column('timestamp', sa.DateTime(), nullable=False))
    op.drop_constraint('commits_hash_key', 'commits', type_='unique')
    op.create_unique_constraint(None, 'commits', ['short_hash'])
    op.create_foreign_key(None, 'commits', 'commits', ['parent_id'], ['id'])
    op.create_foreign_key(None, 'commits', 'branches', ['branch_id'], ['id'])
    op.drop_column('commits', 'branch')
    op.drop_column('commits', 'created_at')
    op.drop_column('commits', 'parent_hash')
    op.drop_column('commits', 'hash')
    op.add_column('documents', sa.Column('title', sa.String(length=255), nullable=False))
    op.add_column('documents', sa.Column('doc_type', sa.String(length=20), nullable=False))
    op.alter_column('documents', 'part_number',
               existing_type=sa.VARCHAR(length=100),
               nullable=False)
    op.drop_column('documents', 'name')
    op.drop_column('documents', 'path')
    op.drop_column('documents', 'created_at')
    op.drop_column('documents', 'updated_at')
    op.drop_column('documents', 'current_svg_key')
    op.drop_column('documents', 'deleted')
    op.drop_column('repositories', 'vault_mode')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('repositories', sa.Column('vault_mode', sa.VARCHAR(length=20), autoincrement=False, nullable=False))
    op.add_column('documents', sa.Column('deleted', sa.BOOLEAN(), autoincrement=False, nullable=False))
    op.add_column('documents', sa.Column('current_svg_key', sa.VARCHAR(length=500), autoincrement=False, nullable=True))
    op.add_column('documents', sa.Column('updated_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False))
    op.add_column('documents', sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False))
    op.add_column('documents', sa.Column('path', sa.VARCHAR(length=500), autoincrement=False, nullable=False))
    op.add_column('documents', sa.Column('name', sa.VARCHAR(length=255), autoincrement=False, nullable=False))
    op.alter_column('documents', 'part_number',
               existing_type=sa.VARCHAR(length=100),
               nullable=True)
    op.drop_column('documents', 'doc_type')
    op.drop_column('documents', 'title')
    op.add_column('commits', sa.Column('hash', sa.VARCHAR(length=64), autoincrement=False, nullable=False))
    op.add_column('commits', sa.Column('parent_hash', sa.VARCHAR(length=64), autoincrement=False, nullable=True))
    op.add_column('commits', sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False))
    op.add_column('commits', sa.Column('branch', sa.VARCHAR(length=255), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'commits', type_='foreignkey')
    op.drop_constraint(None, 'commits', type_='foreignkey')
    op.drop_constraint(None, 'commits', type_='unique')
    op.create_unique_constraint('commits_hash_key', 'commits', ['hash'])
    op.drop_column('commits', 'timestamp')
    op.drop_column('commits', 'protocol_violations')
    op.drop_column('commits', 'diff_report')
    op.drop_column('commits', 'is_local')
    op.drop_column('commits', 'short_hash')
    op.drop_column('commits', 'parent_id')
    op.drop_column('commits', 'branch_id')
    op.add_column('commit_files', sa.Column('diff_key', sa.VARCHAR(length=500), autoincrement=False, nullable=True))
    op.add_column('commit_files', sa.Column('svg_key', sa.VARCHAR(length=500), autoincrement=False, nullable=True))
    op.drop_column('commit_files', 'pdf_diff')
    op.drop_column('commit_files', 'content_hash')
    op.drop_column('commit_files', 's3_key_pdf')
    op.drop_column('commit_files', 's3_key_svg')
    op.add_column('bom_entries', sa.Column('child_document_id', sa.UUID(), autoincrement=False, nullable=False))
    op.add_column('bom_entries', sa.Column('parent_document_id', sa.UUID(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'bom_entries', type_='foreignkey')
    op.drop_constraint(None, 'bom_entries', type_='foreignkey')
    op.create_foreign_key('bom_entries_child_document_id_fkey', 'bom_entries', 'documents', ['child_document_id'], ['id'])
    op.create_foreign_key('bom_entries_parent_document_id_fkey', 'bom_entries', 'documents', ['parent_document_id'], ['id'])
    op.drop_column('bom_entries', 'find_number')
    op.drop_column('bom_entries', 'component_id')
    op.drop_column('bom_entries', 'assembly_id')
    op.add_column('audit_events', sa.Column('event_type', sa.VARCHAR(length=50), autoincrement=False, nullable=False))
    op.add_column('audit_events', sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False))
    op.drop_column('audit_events', 'is_breach')
    op.drop_column('audit_events', 'ip_address')
    op.drop_column('audit_events', 'entity_id')
    op.drop_column('audit_events', 'entity_type')
    op.drop_column('audit_events', 'action')
    op.drop_column('audit_events', 'timestamp')
    op.drop_table('branches')
    # ### end Alembic commands ###
