import uuid
from datetime import datetime
from typing import Any
from pydantic import BaseModel


class RepositoryCreate(BaseModel):
    # fields the API caller must provide when creating a repository
    name: str
    description: str | None = None
    remote_url: str | None = None


class RepositoryResponse(BaseModel):
    # fields returned by the API — includes the id and created_at generated by the server
    id: uuid.UUID
    name: str
    description: str | None
    remote_url: str | None
    created_at: datetime

    class Config:
        # allows Pydantic to read from SQLAlchemy model attributes directly
        from_attributes = True


class RepositoryListResponse(RepositoryResponse):
    # extends the base response with runtime-computed statistics
    document_count: int = 0                  # total documents in this repo
    latest_commit: dict[str, Any] | None = None  # most recent commit info, or None if no commits
