import uuid
from datetime import datetime
from typing import Any
from pydantic import BaseModel


class RepositoryCreate(BaseModel):
    name: str
    description: str | None = None
    remote_url: str | None = None
    # folder to track — relative to home directory, set once like git init
    watch_path: str | None = None


class RepositoryUpdate(BaseModel):
    remote_url: str | None = None
    # which remote repo to link to; None = create a new one on the remote (use
    # this repo's own id). Only applied when remote_url is provided.
    remote_repo_id: uuid.UUID | None = None


class RepositorySettingsUpdate(BaseModel):
    # a sample part number; the format template is derived from it.
    # empty/None clears the configured format.
    part_number_example: str | None = None


class RepositoryResponse(BaseModel):
    # fields returned by the API — includes the id and created_at generated by the server
    id: uuid.UUID
    name: str
    description: str | None
    remote_url: str | None
    remote_repo_id: uuid.UUID | None = None
    watch_path: str | None = None
    created_at: datetime

    class Config:
        # allows Pydantic to read from SQLAlchemy model attributes directly
        from_attributes = True


class RepositoryListResponse(RepositoryResponse):
    # extends the base response with runtime-computed statistics
    document_count: int = 0                  # total documents in this repo
    latest_commit: dict[str, Any] | None = None  # most recent commit info, or None if no commits
